//  
//  FirstRouter.swift
//  CollectionViewProject
//
//  Created by Даниил Ярмоленко on 26.10.2022.
//
//  This file was generated by I-VIPER Xcode Templates
//  so you can design a more scalable and maintainable
//  design to your iOS projects, see https://github.com/fdorado985/I-VIPER
//

import UIKit

class FirstRouter {
  // MARK: - Properties

  weak var presenter: FirstPresenter?

  // MARK: - Methods

  static func createModule() -> FirstViewController {
    let router = FirstRouter()
    let presenter = FirstPresenter()
    let interactor = FirstInteractor()
    let view = FirstViewController()

    presenter.interactor = interactor
    presenter.router = router
    presenter.view = view
    view.presenter = presenter
    interactor.presenter = presenter
    router.presenter = presenter

    return view
  }
}

// MARK: - FirstRouterInterface

extension FirstRouter: FirstRouterInterface {}
