//  
//  SecondPresenter.swift
//  CollectionViewProject
//
//  Created by Даниил Ярмоленко on 26.10.2022.
//
//  This file was generated by I-VIPER Xcode Templates
//  so you can design a more scalable and maintainable
//  design to your iOS projects, see https://github.com/fdorado985/I-VIPER
//

import UIKit

class SecondPresenter {
  // MARK: - Properties

  weak var view: SecondViewInterface?
  var interactor: SecondInteractorInterface?
  var router: SecondRouterInterface?
}

// MARK: - SecondPresenterInterface

extension SecondPresenter: SecondPresenterInterface {}
