//  
//  SecondInteractor.swift
//  CollectionViewProject
//
//  Created by Даниил Ярмоленко on 26.10.2022.
//
//  This file was generated by I-VIPER Xcode Templates
//  so you can design a more scalable and maintainable
//  design to your iOS projects, see https://github.com/fdorado985/I-VIPER
//

import Foundation

class SecondInteractor {
  // MARK: - Properties

  weak var presenter: SecondPresenterInterface?
}

// MARK: - SecondInteractorInterface

extension SecondInteractor: SecondInteractorInterface {}
