//  
//  FirstPresenter.swift
//  CollectionViewProject
//
//  Created by Даниил Ярмоленко on 26.10.2022.
//
//  This file was generated by I-VIPER Xcode Templates
//  so you can design a more scalable and maintainable
//  design to your iOS projects, see https://github.com/fdorado985/I-VIPER
//

import UIKit

class FirstPresenter {
  // MARK: - Properties

  weak var view: FirstViewInterface?
  var interactor: FirstInteractorInterface?
  var router: FirstRouterInterface?
}

// MARK: - FirstPresenterInterface

extension FirstPresenter: FirstPresenterInterface {}
