//  
//  SecondRouter.swift
//  CollectionViewProject
//
//  Created by Даниил Ярмоленко on 26.10.2022.
//
//  This file was generated by I-VIPER Xcode Templates
//  so you can design a more scalable and maintainable
//  design to your iOS projects, see https://github.com/fdorado985/I-VIPER
//

import UIKit

class SecondRouter {
  // MARK: - Properties

  weak var presenter: SecondPresenter?

  // MARK: - Methods

  static func createModule() -> SecondViewController {
    let router = SecondRouter()
    let presenter = SecondPresenter()
    let interactor = SecondInteractor()
    let view = SecondViewController()

    presenter.interactor = interactor
    presenter.router = router
    presenter.view = view
    view.presenter = presenter
    interactor.presenter = presenter
    router.presenter = presenter

    return view
  }
}

// MARK: - SecondRouterInterface

extension SecondRouter: SecondRouterInterface {}
